### ISSUE TITLE
关于PR的小疑问：如何添加补充的词典网站

### ISSUE THREAD

**Issue by NoHeartPen** [Dictionaryphile/All_Dictionaries#11]
请问如果要补充日语词典网站的话，是在已有的词典后面接着写即可么？我看已有的内容似乎不是按照网站名称首字母排序的。

翻了下issue没有找到类似的提问，只看到有人留言词典网站然后由一个人您手动补充的记录；

PR里面也没有可以模仿的例子，所以想问一下。

**Comment by Dictionaryphile** [comment]
您提到的两种做法都可以哈。
