### ISSUE TITLE
俄语词典 gramota.ru

### ISSUE THREAD

**Issue by SyzygyYuan** [Dictionaryphile/All_Dictionaries#6]
日语词频 http://nlt.tsukuba.lagoinst.info/search/
The Century Dictionary http://www.global-language.com/CENTURY/
臺灣閩南語常用詞辭典 http://twblg.dict.edu.tw/holodict_new/index.html
异体字字典 http://dict.variants.moe.edu.tw
WWWJDIC日语词典 http://www.edrdg.org/cgi-bin/wwwjdic/wwwjdic
夏威夷语词典 http://wehewehe.org
说文 http://www.shuowen.org
je海 日英词典 http://jekai.org

**Comment by SyzygyYuan** [comment]
略字Wiki https://seesaawiki.jp/ryakuji/
広辞苑免费检索 https://sakura-paris.org/dict/ 有多种辞书
漢字と古典の総合サイト、字源 jigen.net

**Comment by SyzygyYuan** [comment]
Latin-English http://humanum.arts.cuhk.edu.hk/Lexis/Latin/
MOJi 辞书 https://briefo.tech/
かくなび https://kaku-navi.com/
文字拡大 https://moji.tekkai.com/
読み方は？ https://yomikatawa.com/
OJAD 声调 http://www.gavo.t.u-tokyo.ac.jp/ojad/
平明四字熟語辞典 http://yojijyukugo.com/
複合動詞レキシコン https://db4.ninjal.ac.jp/vvlexicon/
基本動詞ハンドブック　http://verbhandbook.ninjal.ac.jp/
语源由来辞典 http://gogen-allguide.com/
日本語俗語辞書 http://zokugo-dict.com/
故事ことわざ辞典 http://kotowaza-allguide.com/
日本語表現インフォ https://hyogen.info/
違いがわかる事典 https://chigai-allguide.com/
連想類語辞典 https://renso-ruigo.com/
類語辞典・シソーラス・対義語 - Weblio辞書
https://thesaurus.weblio.jp/
汉字古今中外字音查询 https://langwiki.org/tools/dict/
http://f-makuramoto.com/43-syakaika/yomikaki.html
www.dict.com
https://eudict.com/
https://www.wdic.org
http://kanji-database.sourceforge.net/index.html

**Comment by Dictionaryphile** [comment]
- je海 日英词典 http://jekai.org 404
And all others are added. Thank you very much!
